"""Add profession, location, and pictures to Job model

Revision ID: 0e2f40866cc0
Revises: bb340ed70d78
Create Date: 2024-06-24 14:45:18.421784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2f40866cc0'
down_revision = 'bb340ed70d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pictures', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('pictures')
        batch_op.drop_column('location')
        batch_op.drop_column('profession')

    # ### end Alembic commands ###
